"""
tools/embed_disk.py -- convert a DOS 3.3 .dsk floppy image into a C header
byte array for ReRAM embedding (Duke's domain, NEXT_STEPS.md Step 3).

Per CLAUDE.md: "test round-trip correctness (embed a known .dsk, extract it
back byte-for-byte) before trusting it on the real Oregon Trail image." This
module exposes both directions -- embed_to_c_header() and
extract_from_c_header() -- specifically so tests/test_embed_disk.py can
round-trip a synthetic image and catch a wrong sector-boundary/formatting
assumption before it silently corrupts a real game load.

Expected input: a standard 143360-byte (140 KiB) DOS 3.3 / ProDOS 5.25" disk
image (35 tracks x 16 sectors x 256 bytes), already in flat "DOS order" --
see src/disk_sector_layout.h for the layout this assumes and verifies.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOS33_DISK_IMAGE_SIZE = 35 * 16 * 256  # 143360 bytes; must match
                                          # src/disk_sector_layout.h's
                                          # DOS33_DISK_IMAGE_SIZE.

BYTES_PER_LINE = 12


class DiskImageSizeError(ValueError):
    """Raised when a .dsk file is not the expected 140 KiB DOS 3.3 image size."""


def read_dsk_bytes(dsk_path: Path) -> bytes:
    """Read a .dsk file and validate it is a standard 140 KiB DOS 3.3 image.

    Raises DiskImageSizeError if the file size doesn't match
    DOS33_DISK_IMAGE_SIZE -- a wrong-sized image would silently corrupt
    sector-offset math downstream (src/disk_sector_layout.c,
    src/disk_trap.c), so we fail loudly here instead.
    """
    data = dsk_path.read_bytes()
    if len(data) != DOS33_DISK_IMAGE_SIZE:
        raise DiskImageSizeError(
            f"{dsk_path}: expected {DOS33_DISK_IMAGE_SIZE} bytes "
            f"(140 KiB DOS 3.3 image), got {len(data)} bytes"
        )
    return data


def embed_to_c_header(data: bytes, array_name: str) -> str:
    """Convert raw disk image bytes into a C header defining a byte array.

    Emits:
        const uint32_t <array_name>_len = N;
        const uint8_t <array_name>[N] __attribute__((section(".dsk_images"))) = { 0x.., 0x.., ... };

    The __attribute__((section(".dsk_images"))) placement is required:
    linker.ld defines a dedicated .dsk_images output section (ReRAM,
    separate from .rodata) specifically so embedded game images are
    budget-visible and independently relocatable as more games are added
    -- see linker.ld's own comment on that section. Without this
    attribute, GCC/Clang place the array in ordinary .rodata by default,
    silently defeating that entire section (caught 2026-08-01: nothing
    in this file ever emitted the attribute, discovered by inspection
    rather than a build failure, since a plain .rodata placement still
    links and runs fine -- it just isn't the intended, budget-tracked
    region).

    Only the byte array gets the section attribute; the _len constant
    is a 4-byte uint32_t with no reason to consume .dsk_images budget-
    tracking attention, so it stays in ordinary .rodata.

    array_name must be a valid C identifier.
    """
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", array_name):
        raise ValueError(f"invalid C identifier for array_name: {array_name!r}")

    lines = [
        "/* Auto-generated by tools/embed_disk.py -- do not edit by hand. */",
        "#include <stdint.h>",
        "",
        "#ifndef DSK_SECTION",
        "#if defined(__APPLE__)",
        '#define DSK_SECTION __attribute__((section("__DATA,.dsk_images")))',
        "#else",
        '#define DSK_SECTION __attribute__((section(".dsk_images")))',
        "#endif",
        "#endif",
        "",
        f"const uint32_t {array_name}_len = {len(data)}u;",
        f"const uint8_t {array_name}[{len(data)}] DSK_SECTION = {{",
    ]

    for row_start in range(0, len(data), BYTES_PER_LINE):
        row = data[row_start:row_start + BYTES_PER_LINE]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in row)
        lines.append(f"    {hex_bytes},")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def extract_from_c_header(header_text: str, array_name: str) -> bytes:
    """Parse a C header produced by embed_to_c_header() back into raw bytes.

    This is the other half of the round-trip test: embed a known image,
    extract it back, and assert byte-for-byte equality, catching any
    formatting/boundary bug before it reaches a real game image.
    """
    pattern = re.compile(
        r"const\s+uint8_t\s+" + re.escape(array_name) + r"\s*\[\s*\d+\s*\]"
        r"(?:\s*DSK_SECTION|\s*__attribute__\s*\(\(.*?\)\))?\s*=\s*\{(.*?)\};",
        re.DOTALL,
    )
    match = pattern.search(header_text)
    if not match:
        raise ValueError(f"array {array_name!r} not found in header text")

    body = match.group(1)
    hex_values = re.findall(r"0x([0-9A-Fa-f]{2})", body)
    return bytes(int(h, 16) for h in hex_values)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert a .dsk floppy image into a C header byte array."
    )
    parser.add_argument("dsk_path", type=Path, help="path to the .dsk file")
    parser.add_argument("array_name", help="C array identifier, e.g. oregon_trail_dsk")
    parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="output header path (default: stdout)",
    )
    args = parser.parse_args(argv)

    try:
        data = read_dsk_bytes(args.dsk_path)
    except DiskImageSizeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: could not read {args.dsk_path}: {exc.strerror}", file=sys.stderr)
        return 1

    header = embed_to_c_header(data, args.array_name)

    try:
        if args.output:
            args.output.write_text(header)
        else:
            sys.stdout.write(header)
    except OSError as exc:
        print(f"error: could not write {args.output}: {exc.strerror}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
