#!/usr/bin/env python3
"""
tools/extract_apple2_autostart_rom.py -- extracts the real Apple II+
Autostart ROM (apple2-asoft-auto.rom: genuine Applesoft BASIC $D000-
$F7FF + Autostart Monitor $F800-$FFFF) and writes
src/apple2_autostart_rom.h as a first-class, committed, reproducible
asset -- promoted from tools/test_alt_rom_scratch.py's scratch-only
build-scratch/alt_rom_asoft_auto.h, which this project's own
tools/loderunner_altrom_boot.c confirmed is REQUIRED for Lode Runner's
real boot sector to work (the committed src/apple2e_system_rom.h --
Apple IIe Monitor-only, no Applesoft -- crashes on a JMP (indirect)
through an uninitialized zero-page vector Lode Runner's boot code
depends on; see NEXT_STEPS.md for the full diagnosis).

Same real, verified, SHA1-checked source and licensing status as
tools/test_alt_rom_scratch.py (see LICENSE.md's existing entry for
build-scratch/alt_rom_asoft_auto.h) -- this script just promotes it to
a proper src/ header with the same rigor as
tools/extract_apple2e_system_rom.py uses for the IIe ROM.

Usage: python3 tools/extract_apple2_autostart_rom.py
"""
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_HEADER = REPO_ROOT / "src" / "apple2_autostart_rom.h"
ROM_SRC = Path.home() / "devel" / "retrobios" / "bios" / "Apple" / "Apple II" / "apple2-asoft-auto.rom"

# Known real apple2p (Apple II+ Autostart) chip SHA1s, from `mame -listroms
# apple2p`, in $D000-$FFFF address order -- verifies the source file's real
# byte content before treating it as a drop-in Applesoft+Monitor ROM.
EXPECTED_CHUNK_SHA1S = [
    "0287ebcef2c1ce11dc71be15a99d2d7e0e128b1e",  # 341-0011.d0 ($D000)
    "a75ce5aab6401355bf1ab01b04e4946a424879b5",  # 341-0012.d8 ($D800)
    "8d82a1da63224859bd619005fab62c4714b25dd7",  # 341-0013.e0 ($E000)
    "37501be96d36d041667c15d63e0c1eff2f7dd4e9",  # 341-0014.e8 ($E800)
    "e6bf91ed28464f42b807f798fc6422e5948bf581",  # 341-0015.f0 ($F000)
    "a28852ff997b4790e53d8d0352112c4b1a395098",  # 341-0020-00.f8 ($F800, autostart monitor)
]


def main():
    if not ROM_SRC.exists():
        print(f"error: {ROM_SRC} not found", file=sys.stderr)
        print(
            "This ROM is not committed to the repo (same copyright-status "
            "convention as roms/apple2e.zip) -- it must exist locally at "
            "the above path to regenerate src/apple2_autostart_rom.h. If "
            "you have a legitimate copy of apple2-asoft-auto.rom, place it "
            "there and re-run this script.",
            file=sys.stderr,
        )
        sys.exit(1)

    rom_bytes = ROM_SRC.read_bytes()
    print(f"Loaded {ROM_SRC}: {len(rom_bytes)} bytes")
    if len(rom_bytes) != 12288:
        print(f"error: expected 12288 bytes (6x2KB chips), got {len(rom_bytes)}", file=sys.stderr)
        sys.exit(1)

    chunks = [rom_bytes[i:i + 2048] for i in range(0, len(rom_bytes), 2048)]
    for i, (chunk, expected) in enumerate(zip(chunks, EXPECTED_CHUNK_SHA1S)):
        actual = hashlib.sha1(chunk).hexdigest()
        status = "OK" if actual == expected else "MISMATCH"
        print(f"  chunk {i} (${0xD000 + i*2048:04X}): sha1={actual} expected={expected} [{status}]")
        if actual != expected:
            print(f"error: chunk {i} does not match expected real apple2p chip content", file=sys.stderr)
            sys.exit(1)

    print("All 6 chunks verified authentic (Applesoft $D000-$F7FF + Autostart Monitor $F800-$FFFF).")

    # 16KB $C000-$FFFF composite: zero-fill $C000-$CFFF (real Apple II+ has
    # no ROM there -- that's peripheral card I/O space), real ROM content
    # at $D000-$FFFF.
    composite = bytearray(16384)
    composite[0x1000:0x1000 + len(rom_bytes)] = rom_bytes
    assert len(composite) == 16384
    print(f"Composite SHA1: {hashlib.sha1(bytes(composite)).hexdigest()}")

    with open(OUT_HEADER, "w") as f:
        f.write("/* Auto-generated by tools/extract_apple2_autostart_rom.py -- do not\n")
        f.write(" * hand-edit. Real Apple II+ Autostart ROM (apple2-asoft-auto.rom):\n")
        f.write(" * genuine Applesoft BASIC $D000-$F7FF + Autostart Monitor $F800-$FFFF,\n")
        f.write(" * verified authentic via chunk-by-chunk SHA1 against MAME's apple2p\n")
        f.write(" * romset. $C000-$CFFF zero-filled (real Apple II+ has no ROM there --\n")
        f.write(" * that's peripheral-card I/O space). Required for main_qemu_loderunner.c\n")
        f.write(" * (src/apple2e_system_rom.h -- the IIe Monitor-only ROM used by the\n")
        f.write(" * DOS33/Zork boot targets -- crashes on Lode Runner's real boot sector,\n")
        f.write(" * see NEXT_STEPS.md for the diagnosis). */\n")
        f.write("#ifndef APPLE2_AUTOSTART_ROM_H\n#define APPLE2_AUTOSTART_ROM_H\n\n#include <stdint.h>\n\n")
        f.write("static const uint8_t g_apple2_autostart_rom[16384] = {\n")
        for i, b in enumerate(composite):
            f.write(f"0x{b:02X},")
            if (i + 1) % 16 == 0:
                f.write("\n")
        f.write("};\n\n#endif\n")
    print(f"Wrote {OUT_HEADER}")


if __name__ == "__main__":
    main()
