#!/usr/bin/env python3
"""
tools/extract_apple2e_system_rom.py -- extracts the real Apple IIe
16KB system ROM ($C000-$FFFF) from roms/apple2e.zip's two chip files
(342-0134-a.64 = $C000-$DFFF, 342-0135-b.64 = $E000-$FFFF) and writes
src/apple2e_system_rom.h via tools/gen_rom_header.py's C-array format.

Regenerates the file fixed by commit [this session] after discovering
the previously-checked-in src/apple2e_system_rom.h was NOT the real
ROM (~75% bogus 0x00/0xFF filler pattern, mismatching the real chip
files from byte 0). Run this instead of hand-editing that header if
the ROM ever needs regenerating again.

Usage: python3 tools/extract_apple2e_system_rom.py
"""
import hashlib
import subprocess
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ZIP_PATH = REPO_ROOT / "roms" / "apple2e.zip"
OUT_HEADER = REPO_ROOT / "src" / "apple2e_system_rom.h"
EXPECTED_SHA1 = "2bccc27ef975d87c4e712252bd70160cd7c59e4f"


def main():
    with zipfile.ZipFile(ZIP_PATH) as z:
        part_a = z.read("342-0134-a.64")  # $C000-$DFFF, 8192 bytes
        part_b = z.read("342-0135-b.64")  # $E000-$FFFF, 8192 bytes

    rom = part_a + part_b
    if len(rom) != 16384:
        print(f"error: expected 16384 bytes, got {len(rom)}", file=sys.stderr)
        sys.exit(1)

    actual_sha1 = hashlib.sha1(rom).hexdigest()
    if actual_sha1 != EXPECTED_SHA1:
        print(f"error: SHA1 mismatch -- expected {EXPECTED_SHA1}, got {actual_sha1}", file=sys.stderr)
        sys.exit(1)

    tmp_bin = REPO_ROOT / "build" / "_apple2e_system_rom_tmp.bin"
    tmp_bin.parent.mkdir(parents=True, exist_ok=True)
    tmp_bin.write_bytes(rom)

    tmp_header = REPO_ROOT / "build" / "_apple2e_system_rom_tmp.h"
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "tools" / "gen_rom_header.py"), str(tmp_bin), str(tmp_header)],
        check=True,
    )

    body = tmp_header.read_text()
    idx = body.index("static const")
    doc_comment = f"""/* Auto-generated by tools/extract_apple2e_system_rom.py from
 * roms/apple2e.zip's 342-0134-a.64 ($C000-$DFFF) + 342-0135-b.64
 * ($E000-$FFFF) -- do not hand-edit, re-run that script instead.
 *
 * Real Apple IIe System ROM, 16384 bytes = 8192B Part A + 8192B Part B.
 * Verified authentic: SHA1 {actual_sha1}, confirmed via
 * `mame -verifyroms apple2e` (both chip files pass; only the unrelated
 * sc01a.bin speech-synthesizer ROM in that same romset reports a
 * mismatch, which this project doesn't use).
 *
 * NOT covered by this project's MIT license -- copyrighted Apple
 * Computer, Inc. firmware, same category as roms/apple2e.zip itself
 * (see LICENSE's exceptions list). Included only for development/
 * testing (real Apple II boot-ROM emulation, see
 * src/main_qemu_dos33boot.c / src/main_qemu_zork1boot.c).
 *
 * HISTORY: a prior checked-in version of this file (pre-2026-08-02) was
 * NOT actually the real ROM -- ~75% of it was a bogus 0x00/0xFF
 * alternating filler pattern rather than real 6502 code (confirmed by
 * direct byte comparison against the real chip files in
 * roms/apple2e.zip, which mismatched starting at offset 0). This was
 * discovered while debugging why main_qemu_dos33boot.c's real COUT
 * implementation (fable-5's emu_trace finding, dd86358) appeared to
 * write correct characters to screen memory in isolation but produced
 * garbage when driven by the "real" ROM code under full QEMU boot --
 * the ROM code calling COUT was itself fake, explaining the
 * inconsistent/garbage bytes observed. Regenerated from the genuine
 * chip files this time, with the SHA1 above independently verified. */
#ifndef APPLE2E_SYSTEM_ROM_H
#define APPLE2E_SYSTEM_ROM_H

#include <stdint.h>

"""
    OUT_HEADER.write_text(doc_comment + body[idx:])
    tmp_bin.unlink()
    tmp_header.unlink()
    print(f"wrote {OUT_HEADER} ({len(rom)} bytes, SHA1 {actual_sha1})")


if __name__ == "__main__":
    main()
