#!/usr/bin/env python3
"""
tools/gen_charrom_header.py -- extracts the real Apple IIe character
generator ROM (342-0133-a.chr, 4096 bytes) from roms/apple2e.zip and
emits src/charrom_342_0133_a.h, a C byte array for
src/text_apple2.c's glyph renderer.

Real, MAME-verified ROM identity (confirmed via `mame -verifyroms apple2e`
and a direct SHA1 check against MAME's own romset database, not assumed):
  342-0133-a.chr, 4096 bytes,
  SHA1 7060de104046736529c1e8a687a0dd7b84f8c51b

NOT covered by this project's MIT license -- copyrighted Apple Computer,
Inc. firmware, same exceptions-list category as roms/apple2e.zip itself
(see LICENSE). Included only for development/testing (real Apple II
text-mode rendering verification).

Usage: python3 tools/gen_charrom_header.py [roms/apple2e.zip]
"""
from __future__ import annotations
import hashlib
import sys
import zipfile
from pathlib import Path

EXPECTED_SHA1 = "7060de104046736529c1e8a687a0dd7b84f8c51b"
EXPECTED_SIZE = 4096
ENTRY_NAME = "342-0133-a.chr"
OUT_PATH = Path("src/charrom_342_0133_a.h")


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    zip_path = Path(args[0]) if args else Path("roms/apple2e.zip")

    if not zip_path.exists():
        print(f"error: {zip_path} not found -- this ROM zip is not "
              f"committed to git (see LICENSE's exceptions list), it must "
              f"be sourced locally first.", file=sys.stderr)
        return 1

    with zipfile.ZipFile(zip_path) as zf:
        data = zf.read(ENTRY_NAME)

    if len(data) != EXPECTED_SIZE:
        print(f"error: {ENTRY_NAME} is {len(data)} bytes, expected {EXPECTED_SIZE}",
              file=sys.stderr)
        return 1

    actual_sha1 = hashlib.sha1(data).hexdigest()
    if actual_sha1 != EXPECTED_SHA1:
        print(f"error: {ENTRY_NAME} SHA1 mismatch -- expected "
              f"{EXPECTED_SHA1}, got {actual_sha1}. Refusing to generate "
              f"a header from an unverified/wrong ROM file.", file=sys.stderr)
        return 1

    lines = [
        "/* Auto-generated by tools/gen_charrom_header.py from "
        "roms/apple2e.zip's 342-0133-a.chr -- do not hand-edit.",
        " *",
        " * Real Apple IIe character generator ROM, 4096 bytes = 512 "
        "glyph definitions x 8 bytes/glyph (8 scanlines per",
        " * character cell). Verified authentic: SHA1 "
        f"{EXPECTED_SHA1}, matches MAME's own apple2e romset entry",
        " * for 342-0133-a.chr exactly (checked via `mame -verifyroms "
        "apple2e` + a direct SHA1 comparison, not assumed).",
        " *",
        " * NOT covered by this project's MIT license -- copyrighted "
        "Apple Computer, Inc. firmware, same category as",
        " * roms/apple2e.zip itself (see LICENSE's exceptions list). "
        "Included only for development/testing (real Apple",
        " * II text-mode glyph rendering, see src/text_apple2.c). */",
        "#ifndef CHARROM_342_0133_A_H",
        "#define CHARROM_342_0133_A_H",
        "#include <stdint.h>",
        "",
        f"#define CHARROM_342_0133_A_SIZE {len(data)}",
        f"static const uint8_t charrom_342_0133_a[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join(str(b) for b in data[i:i + 16]) + ",")
    lines += ["};", "#endif"]

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}: {len(data)} bytes, SHA1 {actual_sha1} (verified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
