#!/usr/bin/env python3
"""
tools/gen_reinette_rom_headers.py -- embeds third_party/reinette-II-plus/
rom/appleII+.rom and rom/diskII.rom as C arrays (src/reinette/
reinette_roms.h), since this bare-metal RISC-V target has no filesystem
to fopen() them from at runtime (reinette_core.c's readMem()/writeMem()
expect reinette_rom[]/reinette_sl6[] to already be populated in memory,
matching this project's own apple2e_system_rom.h / dos33_nib_disk_data.h
embedding pattern).

appleII+.rom (12288 bytes) is the real Apple II+ Autostart ROM
(Applesoft BASIC $D000-$F7FF + Autostart Monitor $F800-$FFFF) --
independently SHA1-verified earlier this session (2026-08-02) against
`mame -listroms apple2p`'s known chip checksums as a byte-for-byte
concatenation of 341-0011/12/13/14/15 + 341-0020-00.

diskII.rom (256 bytes) is the real Disk ][ P5A boot PROM
(341-0027-a.p5), matches `mame -listroms apple2p`'s sc01a-adjacent
341-0027-a.p5 entry.
"""
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROM_DIR = REPO_ROOT / "third_party" / "reinette-II-plus" / "rom"
OUT_HEADER = REPO_ROOT / "src" / "reinette" / "reinette_roms.h"

ROMS = [
    ("appleII+.rom", "g_reinette_appleII_plus_rom", 12288),
    ("diskII.rom", "g_reinette_diskII_rom", 256),
]


def main():
    lines = [
        "#ifndef REINETTE_ROMS_H",
        "#define REINETTE_ROMS_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Auto-generated by tools/gen_reinette_rom_headers.py from",
        " * third_party/reinette-II-plus/rom/*.rom -- do not hand-edit.",
        " * See that script's docstring for provenance/verification notes.",
        " */",
        "",
    ]

    for filename, array_name, expected_size in ROMS:
        rom_path = ROM_DIR / filename
        data = rom_path.read_bytes()
        if len(data) != expected_size:
            print(f"error: {filename} is {len(data)} bytes, expected {expected_size}", file=sys.stderr)
            return 1
        sha1 = hashlib.sha1(data).hexdigest()
        lines.append(f"/* {filename}: {len(data)} bytes, sha1={sha1} */")
        lines.append(f"static const uint8_t {array_name}[{len(data)}] = {{")
        row = []
        for i, b in enumerate(data):
            row.append(f"0x{b:02X},")
            if (i + 1) % 16 == 0:
                lines.append("".join(row))
                row = []
        if row:
            lines.append("".join(row))
        lines.append("};")
        lines.append("")

    lines.append("#endif /* REINETTE_ROMS_H */")
    lines.append("")

    OUT_HEADER.write_text("\n".join(lines))
    print(f"Wrote {OUT_HEADER} ({OUT_HEADER.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
